[package]
name = "fshamer"
version = "0.1.0"
authors = ["lpasselin <louisphilippeasselin@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2"
structopt = "0.2"
termion = "1.5"
number_prefix = "0.2"
